steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$BUILD_ID', '.']

    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$BUILD_ID']

    - name: 'gcr.io/cloud-builders/gcloud'
      args: ['beta', 'run', 'deploy', 'hello', '--image', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$BUILD_ID', '--region', '${_RUN_REGION}']

    - name: 'gcr.io/cloud-builders/kubectl'
      args: ['set', 'image', '${_CONTAINER_NAME}=gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$BUILD_ID']

      env:
          - 'CLOUDSDK_COMPUTE_ZONE=${_CLUSTER_REGION}'
          - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'  

images:
- 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$BUILD_ID'

substitutions:
    _IMAGE_NAME: my-image
    _CONTAINER_NAME: my-containers
    _CLUSTER_NAME: my-cluster-1
    _CLUSTER_REGION: us-central1-a
    _RUN_REGION: us-central1
